---
- name: Include easybuild
  ansible.builtin.import_playbook: ../../head-node/easybuild.yaml

- name: Force install alphafold
  hosts: localhost
  tasks:
    - name: Install easybuild modules
      become: yes
      become_user: ec2-user
      ansible.builtin.shell: |
        source /usr/share/lmod/lmod/init/bash

        export EASYBUILD_PREFIX=/apps/easybuild/4.5.4
        export MODULEPATH=/apps/easybuild/4.5.4/modules/all
        export ROBOT=/apps/software-configs/bioanalyze-easyconfigs
        
        module purge
        
        source activate easybuild4

        export SBATCH_EXCLUSIVE=""

        cd ${ROBOT}
        rm -rf /apps/easybuild/4.5.4/software/.locks
        export EASYBUILD_JOB_BACKEND='Slurm'
        eb --robot=${ROBOT}: --job  \
          --tmp-logdir $HOME/eb_tmplogs \
          --force \
          easybuild/easyconfigs/alphafold/alphafold-2.2.2.eb
