---
- name: Include easybuild
  ansible.builtin.import_playbook: ../../head-node/easybuild.yaml

- name: Force install jupyterlab
  hosts: localhost
  tasks:
    - name: Install easybuild modules
      ansible.builtin.shell: |
        source /usr/share/lmod/lmod/init/bash

        export EASYBUILD_PREFIX=/apps/easybuild/4.5.4
        export MODULEPATH=/apps/easybuild/4.5.4/modules/all
        export ROBOT=/apps/software-configs/bioanalyze-easyconfigs
        
        module purge
        
        source activate easybuild4

        export SBATCH_EXCLUSIVE=""

        cd ${ROBOT}
        export EASYBUILD_JOB_BACKEND='Slurm'
        eb --robot=${ROBOT}: --job  \
          --tmp-logdir $HOME/eb_tmplogs \
          --force \
          easybuild/easyconfigs/miniconda3-4.12.0.eb \
          easybuild/easyconfigs/r-datascience-4.eb \
          easybuild/easyconfigs/pangeo-notebook-2022.05.10/jupyterlab-2022.05.10.eb
